# Generated by Django 5.2.11 on 2026-05-31 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('simplified_text', models.TextField(blank=True, default='')),
                ('pipeline_result', models.JSONField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_name', models.CharField(default='', max_length=255)),
                ('matched_name', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_brand', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_generic', models.CharField(blank=True, default='', max_length=255)),
                ('match_score', models.FloatField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('price_data', models.JSONField(blank=True, null=True)),
                ('cheapest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cheapest_source', models.CharField(blank=True, default='', max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.prescription')),
            ],
        ),
    ]
